Models/Blog.cs
using System;
namespace OnlineJwellery_Shopping.Models
{
    public class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Thumbnail { get; set; }
        public string Content { get; set; }
        public DateTime BlogDate { get; set; }
        public string Tag { get; set; }
    }
}

Models/Category.cs
using System;
namespace OnlineJwellery_Shopping.Models
{
        public class Category
        {
            public int CategoryId { get; set; }
            public string CategoryName { get; set; }
            public string Slug { get; set; }

        // Navigation property
        public ICollection<Product> Products { get; set; }
        }
    
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineJwellery_Shopping.Models;
using System.Diagnostics;

namespace OnlineJwellery_Shopping.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineJwellery_Shopping.Models;
using OnlineJwellery_Shopping.Data;
using Microsoft.AspNetCore.Http;
using OnlineJwellery_Shopping.Models.Authentication;
using Microsoft.EntityFrameworkCore;
using BCrypt.Net;
using System;
using System.Text;
using OnlineJwellery_Shopping.Heplers;
using System.Threading.Tasks;
using System.Net;
using System.Net.Mail;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnlineJwellery_Shopping.Controllers
{
    public class PageController : BaseController
    {
        private readonly JwelleryShoppingContext db;
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _env;


        public PageController(JwelleryShoppingContext context, IConfiguration configuration, IWebHostEnvironment env) : base(context)
        {
            db = context;
            _configuration = configuration;
            _env = env;
        }
        // GET: /<controller>/
        [Authentication]
        public async Task<IActionResult> Home()
        {
            // kế thừa các logic chung từ BaseController
            await SetCommonViewData();

            return View();
        }
        // search
        public async Task<IActionResult> Search(string searchString)
        {
            // Query all products
            var productsQuery = db.Product.Include(p => p.Category).AsQueryable();
            var distinctCategories = await db.Category.ToListAsync();
            // kế thừa các logic chung từ BaseController
            await SetCommonViewData();


            // Filter by category, price, and product name
            if (!string.IsNullOrEmpty(searchString))
            {
                productsQuery = productsQuery.Where(p =>
                    p.Category.CategoryName.Contains(searchString) ||
                    p.ProductName.Contains(searchString) ||
                    p.Price.ToString().Contains(searchString)
                );
            }

            // Retrieve the filtered products
            var filteredProducts = await productsQuery.ToListAsync();

            // Khởi tạo ViewBag.ProductAverageRating
            ViewBag.ProductAverageRating = new Dictionary<int, double>();


            foreach (var product in filteredProducts)
            {
                var approvedReviewsCount = await _context.Review.CountAsync(r => r.ProductId == product.ProductId && r.Status == "approved");
                var totalStars = await _context.Review
                    .Where(r => r.ProductId == product.ProductId && r.Status == "approved")
                    .SumAsync(r => r.RatingValue);
                double averageRating = approvedReviewsCount > 0 ? (double)totalStars / approvedReviewsCount : 0;
                ViewBag.ProductAverageRating[product.ProductId] = averageRating;
            }

            // Pass the filtered products to the view
            ViewBag.SearchResults = filteredProducts;

            return View(filteredProducts);
        }

       
        [Authentication]
        public async Task<IActionResult> Details(string slug)
        {
            // Kế thừa các logic chung từ BaseController
            await SetCommonViewData();


            // Lấy chi tiết sản phẩm từ cơ sở dữ liệu dựa trên Slug được cung cấp
            var product = await db.Product
                .Include(p => p.Category)
                .Include(p => p.Brand)
                .Include(p => p.GoldAge)
                .FirstOrDefaultAsync(p => p.Slug == slug);

            if (product == null)
            {
                // Xử lý trường hợp không tìm thấy sản phẩm với Slug cụ thể
                return NotFound();
            }

            // Lấy các sản phẩm liên quan
            var relatedProducts = await db.Product
                .Where(p => p.CategoryId == product.CategoryId && p.ProductId != product.ProductId)
                .Take(4) // Số lượng sản phẩm liên quan bạn muốn hiển thị
                .ToListAsync();

            ViewBag.RelatedProducts = relatedProducts;

            // Lấy số lượng sản phẩm đã bán của sản phẩm hiện tại
            var soldQuantity = await db.OrderProduct
                .Where(op => op.Order.Status == "complete" && op.ProductId == product.ProductId)
                .SumAsync(op => op.Qty);

            ViewBag.SoldQuantity = soldQuantity;

            // Đếm số lượng đánh giá đã được duyệt
            var approvedReviewsCount = await _context.Review.CountAsync(r => r.ProductId == product.ProductId && r.Status == "approved");

            // Tính tổng số sao từ tất cả đánh giá đã được duyệt
            var totalStars = await _context.Review
                .Where(r => r.ProductId == product.ProductId && r.Status == "approved")
                .SumAsync(r => r.RatingValue);

            // Tính trung bình cộng số sao
            double averageRating = approvedReviewsCount > 0 ? (double)totalStars / approvedReviewsCount : 0;

            ViewBag.AverageRating = averageRating;
            ViewBag.ApprovedReviewsCount = approvedReviewsCount;


            // Đặt các thuộc tính ViewBag cho chi tiết sản phẩm
            ViewBag.ProductId = product.ProductId;
            ViewBag.ProductThumbnail = product.Thumbnail;
            ViewBag.SmallThumbnail1 = product.SmallThumbnail1;
            ViewBag.SmallThumbnail2 = product.SmallThumbnail2;
            ViewBag.SmallThumbnail3 = product.SmallThumbnail3;
            ViewBag.SmallThumbnail4 = product.SmallThumbnail4;

            ViewBag.ProductName = product.ProductName; // Tên sản phẩm
            ViewBag.ProductPrice = product.Price;      // Giá sản phẩm
            ViewBag.ProductCategory = product.Category?.CategoryName;
            ViewBag.ProductSlug = slug;

            // Đặt các thuộc tính ViewBag cho sự có sẵn của sản phẩm
            ViewBag.ProductAvailability = product.Qty;

            // Đặt thông tin Brand vào ViewBag để sử dụng trong view
            ViewBag.BrandName = product.Brand?.BrandName; // Tên Brand

            // Đặt thông tin GoldAge vào ViewBag để sử dụng trong view
            ViewBag.GoldAge = product.GoldAge?.Age; // Tên GoldAge

            // Đặt các thuộc tính ViewBag cho thông tin khác của sản phẩm
            ViewBag.StoneType = product.StoneType;
            ViewBag.TotalWeight = product.TotalWeight;
            ViewBag.Color = product.Color;
            ViewBag.Size = product.Size;
            ViewBag.Material = product.Material;
            ViewBag.CertificationCode = product.CertificationCode;
            // Lấy tất cả các đánh giá đã được duyệt từ tất cả các tài khoản
            var approvedReviews = await _context.Review
                .Where(r => r.ProductId == product.ProductId && r.Status == "approved")
                .Include(r => r.User) // Lấy thông tin người dùng cho mỗi đánh giá
                .ToListAsync();

            // Lưu danh sách các đánh giá đã được duyệt vào ViewBag
            ViewBag.ApprovedReviews = approvedReviews;


            return View(product);
        }


        public async Task<IActionResult> Category(
        string sortOrder,
        int page = 1,
        int pageSize = 9,
        decimal? minPrice = null,
        decimal? maxPrice = null,
        int? brandId = null,
        int? goldAgeId = null)
        {
            // Kế thừa các logic chung từ BaseController
            await SetCommonViewData();

            // Truy xuất dữ liệu Brand và Gold Age từ cơ sở dữ liệu
            var brands = await _context.Brand.ToListAsync();

            var goldAges = await _context.GoldAge.ToListAsync();

            // Truyền dữ liệu vào view
            ViewBag.Brands = brands;
            ViewBag.GoldAges = goldAges;
            ViewBag.MinPrice = minPrice;
            ViewBag.MaxPrice = maxPrice;
            ViewBag.BrandId = brandId;
            ViewBag.GoldAgeId = goldAgeId;

            // Bắt đầu với một query không có điều kiện lọc
            var query = _context.Product.Include(p => p.Category).AsQueryable();

            // Áp dụng các bộ lọc nếu có
            if (minPrice != null)
            {
                query = query.Where(p => p.Price >= minPrice);
            }

            if (maxPrice != null)
            {
                query = query.Where(p => p.Price <= maxPrice);
            }

            if (brandId != null)
            {
                query = query.Where(p => p.BrandId == brandId);
            }

            if (goldAgeId != null)
            {
                query = query.Where(p => p.GoldAgeId == goldAgeId);
            }

            // Sắp xếp dữ liệu
            switch (sortOrder)
            {
                case "price_asc":
                    query = query.OrderBy(p => (double)p.Price);
                    break;
                case "price_desc":
                    query = query.OrderByDescending(p => (double)p.Price);
                    break;
                case "newest":
                    query = query.OrderByDescending(p => p.ProductId);
                    break;
                case "BestSelling":
                    // Sắp xếp theo số lượng sản phẩm đã bán
                    query = query.OrderByDescending(p =>
                        _context.OrderProduct
                            .Where(op => op.Order.Status == "complete" && op.ProductId == p.ProductId)
                            .Sum(op => op.Qty)
                    );
                    break;

                default:
                    break;
            }

            // Phân trang dữ liệu
            var productList = await query
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            // Tính toán và chuyển thông tin phân trang vào ViewBag hoặc ViewModel
            var totalProductCount = await query.CountAsync();
            ViewBag.TotalProductCount = totalProductCount;

Views/Page/blog.cshtml
@model List<OnlineJwellery_Shopping.Models.Blog>
@{
    Layout = "~/Views/Shared/User_Layout.cshtml";
    ViewData["Title"] = "Blog";
}
<div class="hero-wrap hero-bread" style="background-image: url('/images/anhbg1.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Blog</span></p>
                <h1 class="mb-0 bread">Blog</h1>
            </div>
        </div>
    </div>
</div>

<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <div class="row">
                    @if (Model != null)
                    {
                        @foreach (var blog in Model)
                        {
                            <div class="col-md-12 d-flex ftco-animate">
                                <div class="blog-entry align-self-stretch d-md-flex">
                                    <a href="blog-single.html" class="block-20" style="background-image: url('@blog.Thumbnail');">
                                    </a>
                                    <div class="text d-block pl-md-4">
                                        <div class="meta mb-3">
                                            <div><a href="#">@blog.BlogDate.ToString("MMMM d, yyyy")</a></div>
                                            <div><a href="#">Admin</a></div>
                                            <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                                        </div>
                                        <h3 class="heading"><a href="#">@blog.Title</a></h3>
                                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                                        <p><a href="/Page/BlogDetails/@blog.Id" class="btn btn-primary py-2 px-3">Read more</a></p>
                                    </div>

                                </div>
                            </div>
                        }
                    }
                </div>
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul>
                                <li>
                                    @if (ViewBag.TotalPages > 0)
                                    {
                                        for (int i = 1; i <= ViewBag.TotalPages; i++)
                                        {
                                            <a href="@Url.Action("Blog", new { page = i })">@i</a>
                                        }
                                    }
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar ftco-animate">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon ion-ios-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 CLASS="heading">Categories</h3>
                    <ul class="categories">
                        <li><a href="#">Bags <span>(12)</span></a></li>
                        <li><a href="#">Shoes <span>(22)</span></a></li>
                        <li><a href="#">Dress <span>(37)</span></a></li>
                        <li><a href="#">Accessories <span>(42)</span></a></li>
                        <li><a href="#">Makeup <span>(14)</span></a></li>
                        <li><a href="#">Beauty <span>(140)</span></a></li>
                    </ul>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 CLASS="heading">Recent Blog</h3>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url(/images/product-10.jpg);"></a>
                        <div class="text">
                            <h3 class="heading-1"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> April 09, 2019</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url(/images/product-11.jpg);"></a>
                        <div class="text">
                            <h3 class="heading-1"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> April 09, 2019</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url(/images/product-12.jpg);"></a>
                        <div class="text">
                            <h3 class="heading-1"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> April 09, 2019</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 CLASS="heading">Tag Cloud</h3>
                    <div class="tagcloud">
                        @if (ViewBag.AllTags != null)
                        {
                            @foreach (var tag in ViewBag.AllTags)
                            {
                                <a href="@Url.Action("Blog", "Page", new { tag = tag })" class="tag-cloud-link">@tag</a>
                            }
                        }
                    </div>
                </div>


                <div class="sidebar-box ftco-animate">
                    <h3 class="heading">Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->

Views/Page/contact.cshtml
@{
    Layout = "~/Views/Shared/User_Layout.cshtml";
    ViewData["Title"] = "Contact";
}
<style>
    .alert {
        text-align: center;
        margin: 20px auto;
        width: 100%; /* Điều chỉnh độ rộng của thông báo tùy theo nhu cầu */
    }
</style>
<div class="hero-wrap hero-bread" style="background-image: url('/images/anhbg1.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Contact</span></p>
                <h1 class="mb-0 bread">Contact Us</h1>
            </div>
        </div>
    </div>
</div>
@if (TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}
<section class="ftco-section contact-section bg-light">
    <div class="container">
        <div class="row d-flex mb-5 contact-info">
            <div class="w-100"></div>
            <div class="col-md-3 d-flex">
                <div class="info bg-white p-4">
                    <p><span>Address:</span> <a href="#">Số 8 tôn thất thuyết , Nam Từ Liêm , Hà Nội</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="info bg-white p-4">
                    <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="info bg-white p-4">
                    <p><span>Email:</span> <a href="mailto:info@yoursite.com">winkel@yoursite.com</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="info bg-white p-4">
                    <p><span>Website</span> <a href="#">yoursite.com</a></p>
                </div>
            </div>
        </div>
        <div class="row block-9">
            <div class="col-md-6 order-md-last d-flex">
                <form asp-controller="Page" asp-action="Contact" method="post" class="bg-white p-5 contact-form">
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" placeholder="Your Name">
                    </div>
                    <div class="form-group">
                        <input type="text" name="email" class="form-control" placeholder="Your Email">
                    </div>
                
                    <div class="form-group">
                        <textarea name="message" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                           
                    </div>
                </form>

            </div>

            <div class="col-md-6 d-flex">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.134769004288!2d105.7831221!3d21.0272929!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab4d3a5c327f%3A0xf557678e4efc494e!2zOCBUw7RuIFRo4bqldCBUaHV54bq_dCwgTeG7uSDEkMOsbmgsIE5hbSBU4burIExpw6ptLCBIw6AgTuG7mWk!5e0!3m2!1svi!2s!4v1708520715791!5m2!1svi!2s" width="100%" height="650" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>

        </div>
    </div>
</section> 

Views/Page/login.cshtml
@{
    ViewData["Title"] = "Login Page";
    Layout = "~/Views/Shared/User_Layout.cshtml";
}

@model User
<div class="login-container">
    <div class="login-box">
        <h2>Sign in</h2>
        <div style="margin-left:-50px;">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>


        @using (Html.BeginForm("Login", "Page", FormMethod.Post))
        {
            <div class="input-group">
                <label for="email">Email:</label>
                <i class="fas fa-envelope input-icon"></i>
                @Html.TextBoxFor(x => x.Email, new
                     {

                         type = "text",
                         id = "email",
                         name = "email",
                         required = "required",
                         autofocus = "autofocus"
                      })
            </div>

            <div class="input-group">
                <label for="password">Password:</label>
                <i class="fas fa-lock input-icon"></i>
                @Html.TextBoxFor(x => x.Password, new
                     {

                       type = "password",
                       id = "password",
                       name = "password",
                       required = "required",
                       autofocus = "autofocus"
                     })
            </div>

            <div style="margin-top:20px;" class="remember-password">
                <label><input type="checkbox" name="remember">Remember Me</label>
                <a href="#">Forget Password</a>
            </div>
            <button type="submit" class="btn btn-primary py-3 px-5">Login</button>
        }
        <div class="create-account">
            <p>Create A New Account? <a style="color:#FFA45C;" href="/Page/Register" class="register-link">Sign Up</a></p>
        </div>

    </div>
</div>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background-color: #f2f2f2;
    }

    .login-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .login-box {
        background-color: #fff;
        padding: 40px;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        text-align: center;
        width: 450px;
        margin: 20px;
    }

        .login-box h2 {
            margin-bottom: 20px;
            color: #333;
        }

    .input-group {
        position: relative;
        margin-bottom: 15px;
        text-align: left;
    }

        .input-group input {
            width: 100%;
            padding: 8px;
            padding-left: 30px; /* Thêm đệm bên trái cho phù hợp với biểu tượng */
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        .input-group .input-icon {
            position: absolute;
            left: 8px;
            top: 60%;
        }

    .remember-password {
        font-size: 14px;
        font-weight: 500;
        margin: -15px 0 15px;
        display: flex;
        justify-content: space-between;
    }

        .remember-password label input {
            accent-color: #fff;
            margin-right: 3px;
        }

        .remember-password a {
            text-decoration: none;
        }

            .remember-password a:hover {
                text-decoration: underline;
            }

    .create-account {
        font-size: 14.5px;
        text-align: center;
        margin: 25px;
    }

        .create-account p a {
            color: #fff;
            font-weight: 600px;
            text-decoration: none;
        }

            .create-account p a:hover {
                text-decoration: underline;
            }

    button {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        button:hover {
            background-color: #0056b3;
        }
</style>

Views/Page/search.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Search Product";
    Layout = "~/Views/Shared/User_Layout.cshtml";

}
<div class="search-results-container">
    <h3 class="search-results">@Model.Count Search Results</h3>
</div>

@if (Model != null && Model.Any())
{
    <div class="col-md-8 col-lg-10 order-md-last">
        <div class="row">
            @foreach (var product in Model)
            {
                <div class="col-sm-6 col-md-3 ftco-animate">
                    <div class="product">
                        <a href="#" class="img-prod">
                            <img class="img-fluid" src="@product.Thumbnail" alt="Colorlib Template">
                            <span class="status">30%</span>
                            <div class="overlay"></div>
                        </a>
                        <div class="text py-3 px-3">
                            <h3><a href="@Url.Action("Details", "Page", new { slug = product.Slug })">@product.ProductName</a></h3>

                            <div class="d-flex">
                                <div class="pricing">
                                    <p class="price"><span class="mr-2 price-dc">$120.00</span><span class="price-sale">$@product.Price</span></p>
                                </div>
                                <div class="rating">
                                    @for (int i = 0; i < (int)ViewBag.ProductAverageRating[product.ProductId]; i++)
                                    {
                                        <a href="#"><span class="ion-ios-star star-yellow"></span></a>
                                    }
                                    @if (ViewBag.ProductAverageRating[product.ProductId] - (int)ViewBag.ProductAverageRating[product.ProductId] >= 0.5)
                                    {
                                        <a href="#"><span class="ion-ios-star star-yellow ion-ios-star-half"></span></a>
                                    }
                                    @for (int i = 0; i < 5 - (int)ViewBag.ProductAverageRating[product.ProductId] - ((ViewBag.ProductAverageRating[product.ProductId] - (int)ViewBag.ProductAverageRating[product.ProductId] >= 0.5 ? 1 : 0)); i++)
                                    {
                                        <a href="#"><span class="ion-ios-star-outline star-yellow"></span></a>
                                    }
                                </div>
                            </div>
                            <p class="bottom-area d-flex px-3">
                                <a href="#" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a>
                                <a href="#" class="buy-now text-center py-2">Buy now<span><i class="ion-ios-cart ml-1"></i></span></a>
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}
else
{
    <p>No results found.</p>
}
<style>
    .search-results-container {
        text-align: center; /* Căn giữa nội dung */
        margin-bottom: 20px; /* Khoảng cách dưới tiêu đề */
    }

    .search-results {
        display: inline-block; /* Để margin có hiệu lực */
    }

    .order-md-last {
        margin-left: 130px;
    }

</style>
<style>
    .star-yellow {
        color: gold; /* Đổi màu của sao sang màu vàng */
    }
</style>